version: '3.8'
services: 
  typedb-server:
    build: 
      context: .
      dockerfile: ./typedb/Dockerfile
    container_name: typedb-server
    volumes: 
      - ./typedb:/app
    ports:
      - 1729:1729
  
      
  typedb-console:
    build: 
      context: .
      dockerfile: ./typedb/console_dockerfile/Dockerfile
    container_name: typedb-console
    depends_on: 
      - typedb-server
    

  rasa:
    build: .
    container_name: rasa
    ports: 
        - 5005:5005
    volumes: 
        - ./:/app
    depends_on: 
      - typedb-console
      - typedb-server
    environment: 
      - HOST=typedb-server
    
  action-server:
    container_name: action_server
    build: 
      context: .
      dockerfile: ./actions/Dockerfile
    ports: 
        - 5055:5055

   

  
