define 

#entities 

product sub entity,
    owns Product_RMIT,
    owns Segment,
    owns TCSS,
    owns AT_Site,
    owns Division,
    owns Package_Tech,
    owns Chip_Attach,
    owns Tester_Platform,
    owns cycle,
    owns Phase,
    owns WW,
    owns comment;

#Attribute

Product_RMIT sub attribute,
    value string;

Segment sub attribute,
    value string;

TCSS sub attribute,
    value string;

AT_Site sub attribute,
    value string;

Division sub attribute,
    value string;

Package_Tech sub attribute,
    value string;

Chip_Attach sub attribute,
    value string;

Tester_Platform sub attribute,
    value string;

cycle sub attribute,
    value string;

Phase sub attribute,
    value string;

WW sub attribute,
    value string;

comment sub attribute,
    value string;
