define 

#entities 

product sub entity,
    plays include_cycle:product,
    plays include_phase:product,
    plays include_comment:product,
    plays include_testerplatform:product,
    plays include_segment:product,
    plays include_division:product,
    owns Product_RMIT,
    owns TCSS,
    owns AT_Site,
    owns Package_Tech,
    owns Chip_Attach;

cycle_info sub entity,
    plays include_cycle:cycle,
    plays include_comment:cycle,
    owns cycle;

phase_info sub entity,
    plays include_phase:phase,
    plays include_comment:phase,
    owns Phase;

comment_info sub entity,
    plays include_comment:comment,
    owns WW,
    owns comment;

testerplatform_info sub entity,
    plays include_testerplatform:Tester_Platform,
    owns Tester_Platform;

segment_info sub entity,
    plays include_segment:Segment,
    owns Segment;

division_info sub entity,
    plays include_division:Division,
    owns Division;

include_cycle sub relation,
    relates product,
    relates cycle;

include_comment sub relation,
    relates product,
    relates cycle,
    relates phase,
    relates comment;

include_phase sub relation,
    relates product,
    relates phase;

include_testerplatform sub relation,
    relates product,
    relates Tester_Platform;

include_segment sub relation,
    relates product,
    relates Segment;

include_division sub relation,
    relates product,
    relates Division;

mapping sub entity,
    owns mapping_key,
    owns mapping_value;

mention_mapping sub mapping;
object_type_mapping sub mapping;
attribute_mapping sub mapping;

#Attribute

Product_RMIT sub attribute,
    value string;

Segment sub attribute,
    value string;

TCSS sub attribute,
    value string;

AT_Site sub attribute,
    value string;

Division sub attribute,
    value string;

Package_Tech sub attribute,
    value string;

Chip_Attach sub attribute,
    value string;

Tester_Platform sub attribute,
    value string;

cycle sub attribute,
    value string;

Phase sub attribute,
    value string;

WW sub attribute,
    value string;

comment sub attribute,
    value string;

mapping_key sub attribute,
    value string;

mapping_value sub attribute,
    value string;